### PR TITLE
Update Dockerfile to use recent ubuntu image.

### PR DESCRIPTION
**Pull request by alkmim**
Just a quick update to start using more recent ubuntu images.

### CODE REVIEW

**Comment by jpetazzo** [comment]
I would prefer to tag a specific release; e.g. the 18.04 LTS release, what do you think?

**Comment by alkmim** [comment]
I would be fine with both approaches. The pros and cons of the approaches are:

- With the ubuntu version:

**Comment by alkmim** [comment]
That sounds good to me.

**Comment by jpetazzo** [comment]
Fantastic, thank you!

**Pull request merged**
